spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: "${DB_PASSWORD}"
        url: jdbc:mysql://localhost:3306/brain_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    #      &serverTimezone=UTC
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
#            Only for executing the .sql files from changelog-master.xml file: create -> none -> update
#            ddl-auto: create
#            ddl-auto: none
            ddl-auto: update
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    liquibase:
        change-log: classpath:db/changelog/changelog-master.xml




    mvc:
        hiddenmethod:
            filter:
                enabled: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
            type:
                descriptor:
                    sql:
                        BasicBinder: TRACE