spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: "${DB_PASSWORD}"
        url: jdbc:mysql://localhost:3306/brain_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    #      &serverTimezone=UTC
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
#            ddl-auto: update
            ddl-auto: create-drop
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true




    mvc:
        hiddenmethod:
            filter:
                enabled: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
            type:
                descriptor:
                    sql:
                        BasicBinder: TRACE